name: CI

on:
  push:
  pull_request:

jobs:
  core-and-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Test core
        run: cargo test
        working-directory: core/chaincodec
      - name: Test API
        run: cargo test
        working-directory: services/api

  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/web/package-lock.json
      - name: Install deps
        run: npm install
        working-directory: apps/web
      - name: Build web
        run: npm run build
        working-directory: apps/web

  python-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Test Python SDK
        run: python -m unittest discover -s tests -v
        working-directory: sdk/python
